package dev.aegis.remote.desktop

import androidx.compose.runtime.staticCompositionLocalOf
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

internal enum class DesktopLanguage(
    val persistedValue: String,
    val locale: Locale,
) {
    Spanish("es", Locale.forLanguageTag("es-MX")),
    English("en", Locale.ENGLISH),
    System("system", Locale.getDefault()),
    ;

    fun resolved(): DesktopLanguage =
        when (this) {
            System -> if (Locale.getDefault().language.equals("es", ignoreCase = true)) Spanish else English
            else -> this
        }

    fun text(key: String): String {
        val resolved = resolved()
        return when (resolved) {
            Spanish -> SPANISH_COPY[key]
            English -> ENGLISH_COPY[key]
            System -> null
        } ?: ENGLISH_COPY[key] ?: key
    }

    companion object {
        fun fromPersisted(value: String?): DesktopLanguage =
            when (value?.trim()?.lowercase(Locale.ROOT)) {
                "es", "es-mx", "spanish", "spanishlanguage" -> Spanish
                "en", "en-us", "english" -> English
                "system", "auto", "automatic" -> System
                else -> System
            }
    }
}

internal val LocalDesktopLanguage = staticCompositionLocalOf { DesktopLanguage.System }

internal object DesktopLanguageStore {
    private const val FILE_NAME = "ui-language.txt"

    fun load(): DesktopLanguage =
        runCatching {
            DesktopLanguage.fromPersisted(Files.readString(settingsPath(), StandardCharsets.UTF_8))
        }.getOrDefault(DesktopLanguage.System)

    fun save(language: DesktopLanguage) {
        runCatching {
            val path = settingsPath()
            Files.createDirectories(path.parent)
            val temporary = path.resolveSibling("$FILE_NAME.tmp")
            Files.writeString(temporary, language.persistedValue, StandardCharsets.UTF_8)
            runCatching {
                Files.move(
                    temporary,
                    path,
                    java.nio.file.StandardCopyOption.ATOMIC_MOVE,
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                )
            }.getOrElse {
                Files.move(temporary, path, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
            }
        }
    }

    internal fun settingsPath(): Path {
        val appData =
            System.getenv("APPDATA")?.takeIf { it.isNotBlank() }
                ?: System.getProperty("user.home")
        return Path.of(appData, "Aegis Remote Desktop", FILE_NAME)
    }
}

private val SPANISH_COPY =
    mapOf(
        "permission.visual" to "Ver pantalla",
        "permissions.save" to "Guardar permisos",
        "permissions.hint" to
            "La terminal también permite modificar archivos. Al guardar se reinician las sesiones afectadas; cambiar ese permiso " +
            "cierra todas las conexiones de terminal y archivos.",
        "permissions.files" to "Terminal y archivos",
        "permissions.title" to "Permisos de este teléfono",
        "direct.lifecycle" to "Cerrar esta ventana o elegir Salir termina todos los accesos. Para mantener la conexión, usa Ocultar ventana en la bandeja.",
        "direct.public.guide" to
            "1. Vincula primero el teléfono con el QR.\n\n2. En el router reserva una IP local para este PC. Reenvía TCP 48291 y TCP " +
            "48222 a esa dirección. Conserva los números de puerto o indica los externos en el teléfono.\n\n3. En Android abre tu PC " +
            "› Acceso remoto › IP pública y guarda la IP pública del router o un nombre actualizado. Prueba con datos móviles.\n\nSi " +
            "tu proveedor comparte la IP entre varios hogares, pide una IP pública o usa Conexión sencilla. Si conecta pero no se ve " +
            "la pantalla, usa Conexión sencilla: algunos routers bloquean el video directo.\n\nPermite Aegis en el cortafuegos de tu " +
            "red de confianza. No abras el puerto 22 ni desactives el cortafuegos.",
        "direct.private.guide" to
            "1. Vincula el teléfono con el QR mientras ambos usan el mismo Wi-Fi.\n\n2. Instala Tailscale en el PC y el teléfono. " +
            "Inicia sesión en la misma cuenta y actívalo en ambos.\n\n3. En el teléfono abre tu PC › Acceso remoto y pega la " +
            "dirección del PC que aparece en Tailscale.\n\n4. Pulsa Guardar y comprobar con el Wi-Fi del teléfono apagado. No " +
            "necesitas abrir puertos.",
        "direct.diagnostics" to "Diagnóstico y compatibilidad",
        "direct.local.address" to "Dirección local del PC",
        "direct.public" to "IP pública",
        "direct.simple" to "Conexión sencilla",
        "direct.title" to "Acceso fuera de casa",
        "tray.ready" to "Aegis Remote Desktop · emparejamiento disponible",
        "tray.default" to "Aegis Remote Desktop",
        "tray.menu.open" to "Abrir Aegis",
        "tray.menu.hide" to "Ocultar ventana",
        "tray.menu.status.ready" to "Listo para conectar",
        "tray.menu.status.starting" to "Iniciando…",
        "tray.menu.devices.none" to "Sin dispositivos vinculados",
        "tray.menu.devices.one" to "1 dispositivo vinculado",
        "tray.menu.devices.many" to "%d dispositivos vinculados",
        "tray.menu.pending.one" to "1 solicitud pendiente",
        "tray.menu.pending.many" to "%d solicitudes pendientes",
        "tray.menu.remote_input" to "Entrada remota",
        "tray.menu.clipboard" to "Sincronizar portapapeles",
        "tray.menu.remote_access" to "Acceso fuera de casa",
        "tray.menu.refresh_qr" to "Renovar código QR",
        "tray.menu.copy_code" to "Copiar código de respaldo",
        "tray.menu.copied" to "Copiado",
        "tray.menu.devices_section" to "Dispositivos",
        "tray.menu.activity" to "Actividad",
        "tray.menu.settings" to "Ajustes",
        "tray.menu.exit" to "Salir de Aegis",
        "tray.unavailable.close_exits" to "Sin bandeja del sistema: cerrar la ventana detiene el agente.",
        "action.copy" to "Copiar",
        "action.copied" to "Copiado",
        "brand.subtitle" to "Escritorio remoto",
        "revoke.title" to "Revocar acceso",
        "revoke.body" to "%s dejará de poder iniciar sesiones nuevas. Para recuperarlo tendrás que emparejarlo otra vez.",
        "revoke.action" to "Revocar",
        "delete.title" to "Eliminar registro",
        "delete.body" to "Se eliminará definitivamente el registro revocado de %s. Esta acción no modifica otros dispositivos.",
        "delete.action" to "Eliminar",
        "delete.in_progress" to "Eliminando…",
        "delete.result.deleted" to "Registro revocado eliminado.",
        "delete.result.must_revoke" to "Primero revoca el acceso antes de eliminar el registro.",
        "delete.result.not_found" to "El registro ya no existe.",
        "delete.result.unsupported" to "Este almacén de confianza no permite borrar registros definitivamente.",
        "delete.result.ssh_removal_pending" to "No se puede eliminar el registro mientras la retirada de la clave SSH siga pendiente.",
        "delete.result.failed" to "No se pudo eliminar el registro. Consulta Actividad para ver el diagnóstico.",
        "cancel" to "Cancelar",
        "attention" to "Requiere atención",
        "request.pending.one" to "%d solicitud pendiente",
        "request.pending.many" to "%d solicitudes pendientes",
        "agent.available" to "Agente disponible",
        "agent.starting" to "Iniciando agente",
        "devices.active" to "%d dispositivos activos",
        "section.home.label" to "Inicio",
        "section.home.title" to "Inicio",
        "section.home.subtitle" to "Conecta tu teléfono y revisa el estado esencial del agente.",
        "section.devices.label" to "Dispositivos",
        "section.devices.title" to "Dispositivos",
        "section.devices.subtitle" to "Administra quién puede acceder a esta computadora.",
        "section.activity.label" to "Actividad",
        "section.activity.title" to "Actividad",
        "section.activity.subtitle" to "Aprueba sesiones y consulta eventos recientes.",
        "section.settings.label" to "Ajustes",
        "section.settings.title" to "Ajustes",
        "section.settings.subtitle" to "Configura acceso, privacidad y capacidades del sistema.",
        "status.pending.one" to "%d pendiente",
        "status.pending.many" to "%d pendientes",
        "status.ready" to "Listo para conectar",
        "status.starting" to "Iniciando",
        "pair.title" to "Conectar un teléfono",
        "pair.body" to "Abre Aegis en Android y apunta la cámara. No necesitas copiar códigos ni completar formularios.",
        "pair.qr.ready" to "QR seguro listo para escanear",
        "pair.qr.preparing" to "Preparando conexión local…",
        "pair.qr.refresh" to "Generar un QR nuevo",
        "pair.qr.refreshing" to "Generando QR seguro…",
        "pair.qr.expires" to "El QR caduca en %d s y se renueva solo.",
        "pair.qr.expired" to "El QR caducó; generando uno nuevo…",
        "computer.title" to "Esta computadora",
        "computer.local_details" to "Datos de conexión local",
        "status.online" to "En línea",
        "field.local_address" to "Dirección local",
        "field.detecting_network" to "Detectando red…",
        "field.backup_code" to "Código de respaldo",
        "field.agent_identity" to "Identidad del agente",
        "field.generating_identity" to "Generando identidad…",
        "approval.visible" to "Aprobación visible",
        "approval.visible.body" to "Después del escaneo verás aquí la identidad del teléfono. El acceso solo comienza cuando lo apruebas.",
        "metric.devices" to "Dispositivos",
        "metric.active_access" to "con acceso activo",
        "metric.capture" to "Captura",
        "metric.system_capability" to "capacidad del sistema",
        "metric.remote_input" to "Entrada remota",
        "metric.allowed" to "Permitida",
        "metric.paused" to "Pausada",
        "metric.safety_switch" to "interruptor de seguridad",
        "metric.relay" to "Terminal y archivos",
        "metric.connected" to "Conectado",
        "metric.disconnected" to "Desconectado",
        "metric.outside_lan" to "Acceso desde la app",
        "approval.required" to "Se necesita tu aprobación",
        "approval.verify" to "Comprueba la identidad antes de permitir el acceso.",
        "approval.local_phone" to "Teléfono en la red local · %s",
        "approval.relay_request" to "Solicitud remota · %s",
        "approval.remote_device" to "Dispositivo remoto",
        "approval.permissions" to
            "Pantalla, ratón, teclado, portapapeles, terminal y archivos. El encendido por red solo si el equipo lo admite. El " +
            "acceso por Internet no se concede aquí.",
        "approve.processing" to "Procesando…",
        "reject" to "Rechazar",
        "approve" to "Aprobar",
        "devices.authorized_access" to "Acceso autorizado",
        "devices.none" to "Ningún dispositivo puede controlar esta computadora.",
        "devices.sessions.one" to "1 dispositivo puede iniciar sesiones.",
        "devices.sessions.many" to "%d dispositivos pueden iniciar sesiones.",
        "devices.active_count" to "%d activos",
        "devices.empty.title" to "Aún no hay dispositivos",
        "devices.empty.body" to "Escanea el QR de Inicio y aprueba el teléfono para que aparezca aquí.",
        "devices.authorized" to "Autorizado",
        "devices.revoked" to "Revocado",
        "devices.ssh_removal_pending" to "Retirada SSH pendiente",
        "devices.ssh_removal_pending_detail" to "%s: acceso Aegis bloqueado; la clave SSH sigue pendiente de retirada.",
        "devices.ssh_removal_retry" to "Reintentar retirada SSH",
        "devices.ssh_removal_retrying" to "Retirando clave SSH…",
        "devices.approved_at" to "Aprobado %s",
        "devices.approved_label" to "Aprobado",
        "activity.title" to "Registro del agente",
        "activity.body" to "Eventos locales de conexión, seguridad y capacidades.",
        "activity.events.one" to "1 evento",
        "activity.events.many" to "%d eventos",
        "activity.empty.title" to "Sin actividad todavía",
        "activity.empty.body" to "Los eventos del agente aparecerán aquí cuando haya conexiones o cambios de estado.",
        "log.level.info" to "INFORMACIÓN",
        "log.level.warning" to "AVISO",
        "log.level.error" to "ERROR",
        "settings.relay.title" to "Conexión alternativa",
        "settings.relay.body" to "Configuración de compatibilidad para instalaciones existentes.",
        "settings.relay.url" to "Dirección de conexión *",
        "settings.relay.url.placeholder" to "https://relay.ejemplo.com",
        "settings.relay.id" to "ID de este PC (opcional)",
        "settings.relay.id.placeholder" to "Aegis puede asignarlo automáticamente",
        "settings.relay.saving" to "Guardando…",
        "settings.relay.save" to "Guardar y conectar",
        "settings.relay.remove" to "Quitar conexión alternativa",
        "settings.relay.rotate_identity" to "Renovar clave de conexión",
        "settings.relay.rotate_identity.title" to "Renovar clave",
        "settings.relay.rotate_identity.body" to
            "Se cerrarán las sesiones remotas activas y se creará una clave nueva. La clave anterior autorizará el cambio antes de ser retirada.",
        "settings.relay.rotate_identity.confirm" to "Renovar",
        "settings.relay.guide.title" to "Cómo configurar el relay",
        "settings.relay.guide.summary" to
            "El relay permite que ambos dispositivos se encuentren fuera de tu Wi‑Fi. No recibe contraseñas SSH ni video.",
        "settings.relay.guide.step1" to "1. Ejecuta o despliega el servidor relay detrás de HTTPS.",
        "settings.relay.guide.step2" to "2. Copia su URL aquí y pulsa Guardar y conectar.",
        "settings.relay.guide.step3" to "3. En Android usa la misma URL y el ID de este PC que aparecerá abajo.",
        "settings.relay.guide.security" to
            "Para Internet usa HTTPS/WSS, autenticación del proxy y almacenamiento persistente. Para una prueba local puedes usar http://IP_DEL_PC:8080.",
        "settings.relay.show_guide" to "Ver guía",
        "settings.relay.hide_guide" to "Ocultar guía",
        "settings.access.title" to "Acceso y privacidad",
        "settings.access.body" to "Controla qué puede hacer Aegis en esta computadora.",
        "settings.zoom.title" to "Zoom de interfaz",
        "settings.zoom.body" to "Ajusta el tamaño de la interfaz sin cambiar la resolución de pantalla.",
        "settings.zoom.reset" to "Restablecer a 100%",
        "settings.remote.title" to "Usar conexión alternativa",
        "settings.remote.needs_relay" to "Configura un relay para usar conexiones fuera de tu red local.",
        "settings.remote.ready" to "Permite nuevas sesiones a través del relay configurado.",
        "settings.input.title" to "Entrada de mouse y teclado",
        "settings.input.enabled" to "Los dispositivos aprobados pueden enviar acciones de entrada.",
        "settings.input.paused" to "Pausada: se bloquean las acciones remotas de mouse y teclado.",
        "settings.clipboard.title" to "Sincronización de portapapeles",
        "settings.clipboard.body" to "Comparte texto seguro durante una sesión activa. Desactivado por defecto.",
        "settings.autostart.title" to "Iniciar al entrar al sistema",
        "settings.autostart.available" to "Abre el agente en tu sesión de usuario.",
        "settings.autostart.unavailable" to "No está disponible en este sistema.",
        "settings.displays" to "Pantallas detectadas",
        "settings.display.origin" to "%d × %d · origen %d, %d",
        "settings.display.primary" to "Principal",
        "settings.language.title" to "Idioma",
        "settings.language.body" to "La aplicación usa el idioma del instalador como valor inicial; puedes cambiarlo aquí.",
        "settings.language.system" to "Sistema",
        "settings.language.spanish" to "Español",
        "settings.language.english" to "English",
        "manual.title" to "Datos de conexión manual",
        "manual.body" to "El QR prepara estos datos automáticamente. Consúltalos para configurar una conexión manual.",
        "manual.host" to "Host LAN *",
        "manual.username" to "Usuario del sistema *",
        "manual.fingerprint" to "Código de verificación del equipo",
        "manual.algorithm" to "Algoritmo",
        "manual.credential" to
            "La contraseña o clave privada es obligatoria y solo la proporcionas tú en Android; Aegis nunca la muestra ni la incluye en el QR.",
        "manual.unavailable" to "No disponible",
        "manual.permission" to "Requiere permisos",
        "manual.error" to "No se pudo detectar",
        "settings.application" to "Aplicación",
        "settings.application.body" to "Cerrar la ventana termina las conexiones. Usa Ocultar ventana en la bandeja para mantener el acceso.",
        "settings.exit" to "Salir de Aegis",
        "settings.nav.heading" to "AJUSTES",
        "settings.nav.access" to "Acceso remoto",
        "settings.nav.privacy" to "Privacidad",
        "settings.nav.firewall" to "Cortafuegos",
        "settings.nav.ssh" to "Conexión manual",
        "settings.nav.capabilities" to "Capacidades",
        "settings.nav.displays" to "Pantallas",
        "settings.nav.app" to "Inicio y cierre",
        "trust.recovery.title" to "Hay que recuperar el almacén de confianza",
        "trust.recovery.body" to
            "Las vinculaciones, revocaciones y eliminaciones están bloqueadas para conservar el archivo original. Restaura solo una " +
            "copia de seguridad válida o confirma el reinicio para volver a vincular los dispositivos.",
        "trust.recovery.path" to "Ruta de la copia de seguridad",
        "trust.recovery.path.placeholder" to "C:\\ruta\\authorized-devices.json",
        "trust.recovery.restore" to "Restaurar copia",
        "trust.recovery.reset" to "Reiniciar y volver a vincular",
        "trust.reset.title" to "¿Reiniciar confianza y volver a vincular?",
        "trust.reset.body" to
            "Esta acción sustituirá el almacén no recuperable por uno vacío. Los dispositivos deberán vincularse otra vez. Solo continúa si lo confirmas.",
        "trust.reset.confirm" to "Confirmar reinicio",
        "ufw.title" to "Cortafuegos de la red local",
        "ufw.body" to
            "Las reglas opcionales se añaden solo después de que las revises y autorices. Aegis nunca activa el cortafuegos ni " +
            "cambia su configuración por defecto.",
        "ufw.inspect" to "Revisar la red local activa",
        "ufw.scope" to "Interfaz %s · %s · solo TCP 48291 y 48222",
        "ufw.review" to "Revisar autorización del cortafuegos",
        "ufw.inactive" to "El cortafuegos está inactivo. Aegis no lo activará.",
        "ufw.applied" to "Las reglas de red local ya están presentes.",
        "ufw.consent.title" to "¿Autorizar dos reglas solo para la red local?",
        "ufw.consent.body" to
            "Se añadirán TCP 48291 y TCP 48222 únicamente en %s desde %s. El cortafuegos ya debe estar activo. Aegis no lo activará " +
            "ni cambiará el resto de reglas.",
        "ufw.consent.confirm" to "Autorizar estas reglas",
        "capabilities.title" to "Capacidades del sistema",
        "capabilities.pairing_server" to "Conexión con el teléfono",
        "capabilities.openssh" to "Terminal y archivos",
        "capabilities.capture" to "Captura de pantalla",
        "capabilities.input" to "Control de entrada",
        "relay.title" to "Conexión alternativa",
        "relay.connected" to "Conectado",
        "relay.not_connected" to "Sin conexión",
        "relay.url" to "URL",
        "relay.not_configured" to "No configurado",
        "relay.device_id" to "ID del dispositivo",
        "relay.not_registered" to "No registrado",
        "relay.pending" to "Solicitudes pendientes",
        "status.available" to "Disponible",
        "status.unavailable" to "No disponible",
        "status.checking" to "Comprobando",
        "status.permission_required" to "Requiere permiso",
        "qr.preparing" to "Preparando QR",
        "qr.description" to "Código QR para emparejar Aegis Android",
        "permissions.none" to "Sin permisos activos",
        "permissions.prefix" to "Permisos: %s",
        "permission.screen" to "pantalla",
        "permission.input" to "Ratón y teclado",
        "permission.terminal" to "terminal",
        "permission.files" to "archivos",
        "permission.clipboard" to "Compartir texto",
        "permission.wol" to "Encender el PC",
        "permission.remote" to "acceso remoto",
        "time.now" to "ahora",
        "time.recently" to "recientemente",
        "status.degraded" to "Degradado",
        "home.ssh.unavailable.title" to "Terminal y archivos no están listos",
        "home.ssh.unavailable.body" to
            "El servicio OpenSSH de Aegis no está en ejecución. Reinstala o repara con el instalador elevado para habilitar terminal y archivos.",
        "home.network.public.title" to "Esta red está marcada como Pública",
        "home.network.public.body" to
            "El instalador abre terminal y archivos solo en redes Privadas o de dominio. En Windows, marca esta red como Privada: " +
            "Configuración → Red e Internet → propiedades de la red.",
        "preflight.windows" to "Comprobación de Windows",
        "preflight.linux" to "Comprobación de Linux",
        "preflight.compositor.unknown" to "compositor desconocido",
        "preflight.capability.operating-system" to "Sistema operativo",
        "preflight.capability.architecture" to "Arquitectura",
        "preflight.capability.interactive-session" to "Sesión interactiva",
        "preflight.capability.webrtc-native" to "WebRTC nativo",
        "preflight.capability.desktop-duplication" to "Duplicación de escritorio",
        "preflight.capability.send-input" to "Envío de entrada",
        "preflight.capability.dpapi" to "DPAPI",
        "preflight.capability.openssh-scripts" to "Scripts OpenSSH",
        "preflight.capability.openssh-port" to "Puerto OpenSSH",
        "preflight.capability.network-profile" to "Perfil de red",
        "preflight.capability.data-directory" to "Directorio de datos",
        "preflight.capability.autostart" to "Inicio automático",
        "preflight.capability.capture" to "Captura",
        "preflight.capability.input" to "Entrada",
        "preflight.capability.clipboard" to "Portapapeles",
        "preflight.capability.session" to "Sesión",
        "preflight.capability.compositor" to "Compositor",
        "preflight.capability.xdg-desktop-portal" to "Portal XDG",
        "preflight.capability.portal-backend" to "Backend del portal",
        "preflight.capability.pipewire" to "PipeWire",
        "preflight.capability.dbus-session" to "Bus de sesión D-Bus",
        "preflight.capability.secret-service" to "Servicio de secretos",
        "preflight.capability.sshd" to "sshd",
        "preflight.capability.ssh-keygen" to "ssh-keygen",
        "preflight.capability.xdotool-xtest" to "xdotool / XTEST",
        "preflight.capability.ydotool-socket" to "ydotool",
        "preflight.capability.xclip" to "xclip",
        "preflight.capability.wl-copy" to "wl-copy",
        "preflight.capability.wl-paste" to "wl-paste",
        "preflight.capability.portal-bridge" to "Puente del portal",
        "preflight.network.public.detail" to
            "La red activa es Pública; terminal y archivos (TCP 48222) quedan bloqueados. Márcala como Privada.",
    )

private val ENGLISH_COPY =
    mapOf(
        "permission.visual" to "View screen",
        "permissions.save" to "Save permissions",
        "permissions.hint" to
            "The terminal can also modify files. Saving restarts affected sessions; changing that permission closes all terminal and " +
            "file connections.",
        "permissions.files" to "Terminal and files",
        "permissions.title" to "Permissions for this phone",
        "direct.lifecycle" to "Closing this window or choosing Exit ends all access. Use Hide window in the tray to keep the connection available.",
        "direct.public.guide" to
            "1. Pair your phone using the QR code first.\n\n2. Reserve a local IP for this PC in your router. Forward TCP 48291 and " +
            "TCP 48222 to it. Keep the same numbers or enter the external ports on your phone.\n\n3. On Android open your PC › " +
            "Remote access › Public IP and save the public router IP or an up-to-date name. Test with mobile data.\n\nIf your " +
            "provider shares an IP across homes, request a public IP or use Easy connection. If it connects but the screen is blank, " +
            "use Easy connection: some routers block direct video.\n\nAllow Aegis through the firewall on your trusted network. Do " +
            "not open port 22 or disable the firewall.",
        "direct.private.guide" to
            "1. Pair your phone using the QR code while both devices share Wi-Fi.\n\n2. Install Tailscale on the PC and phone. Sign " +
            "in to the same account and enable it on both.\n\n3. On your phone open your PC › Remote access and paste the PC address " +
            "shown in Tailscale.\n\n4. Select Save and check with phone Wi-Fi off. No router ports are needed.",
        "direct.diagnostics" to "Diagnostics and compatibility",
        "direct.local.address" to "Local PC address",
        "direct.public" to "Public IP",
        "direct.simple" to "Easy connection",
        "direct.title" to "Access away from home",
        "tray.ready" to "Aegis Remote Desktop · pairing available",
        "tray.default" to "Aegis Remote Desktop",
        "tray.menu.open" to "Open Aegis",
        "tray.menu.hide" to "Hide window",
        "tray.menu.status.ready" to "Ready to connect",
        "tray.menu.status.starting" to "Starting…",
        "tray.menu.devices.none" to "No paired devices",
        "tray.menu.devices.one" to "1 paired device",
        "tray.menu.devices.many" to "%d paired devices",
        "tray.menu.pending.one" to "1 pending request",
        "tray.menu.pending.many" to "%d pending requests",
        "tray.menu.remote_input" to "Remote input",
        "tray.menu.clipboard" to "Clipboard sync",
        "tray.menu.remote_access" to "Away-from-home access",
        "tray.menu.refresh_qr" to "Renew QR code",
        "tray.menu.copy_code" to "Copy backup code",
        "tray.menu.copied" to "Copied",
        "tray.menu.devices_section" to "Devices",
        "tray.menu.activity" to "Activity",
        "tray.menu.settings" to "Settings",
        "tray.menu.exit" to "Exit Aegis",
        "tray.unavailable.close_exits" to "No system tray: closing the window stops the agent.",
        "action.copy" to "Copy",
        "action.copied" to "Copied",
        "brand.subtitle" to "Remote Desktop",
        "revoke.title" to "Revoke access",
        "revoke.body" to "%s will no longer be able to start new sessions. Pair it again to restore access.",
        "revoke.action" to "Revoke",
        "delete.title" to "Delete record",
        "delete.body" to "The revoked record for %s will be permanently deleted. Other devices are not affected.",
        "delete.action" to "Delete",
        "delete.in_progress" to "Deleting…",
        "delete.result.deleted" to "Revoked record deleted.",
        "delete.result.must_revoke" to "Revoke access before deleting the record.",
        "delete.result.not_found" to "The record no longer exists.",
        "delete.result.unsupported" to "This trust store cannot permanently delete records.",
        "delete.result.ssh_removal_pending" to "The record cannot be deleted while managed SSH key removal is pending.",
        "delete.result.failed" to "The record could not be deleted. Open Activity for diagnostic details.",
        "cancel" to "Cancel",
        "attention" to "Needs attention",
        "request.pending.one" to "%d pending request",
        "request.pending.many" to "%d pending requests",
        "agent.available" to "Agent available",
        "agent.starting" to "Starting agent",
        "devices.active" to "%d active devices",
        "section.home.label" to "Home",
        "section.home.title" to "Home",
        "section.home.subtitle" to "Connect your phone and review the agent's essential status.",
        "section.devices.label" to "Devices",
        "section.devices.title" to "Devices",
        "section.devices.subtitle" to "Manage who can access this computer.",
        "section.activity.label" to "Activity",
        "section.activity.title" to "Activity",
        "section.activity.subtitle" to "Approve sessions and review recent events.",
        "section.settings.label" to "Settings",
        "section.settings.title" to "Settings",
        "section.settings.subtitle" to "Configure access, privacy, and system capabilities.",
        "status.pending.one" to "%d pending",
        "status.pending.many" to "%d pending",
        "status.ready" to "Ready to connect",
        "status.starting" to "Starting",
        "pair.title" to "Connect a phone",
        "pair.body" to "Open Aegis on Android and point the camera here. No codes or forms are required.",
        "pair.qr.ready" to "Secure QR ready to scan",
        "pair.qr.preparing" to "Preparing local connection…",
        "pair.qr.refresh" to "Generate a new QR",
        "pair.qr.refreshing" to "Generating secure QR…",
        "pair.qr.expires" to "The QR expires in %d s and renews automatically.",
        "pair.qr.expired" to "The QR expired; generating a new one…",
        "computer.title" to "This computer",
        "computer.local_details" to "Local connection details",
        "status.online" to "Online",
        "field.local_address" to "Local address",
        "field.detecting_network" to "Detecting network…",
        "field.backup_code" to "Backup code",
        "field.agent_identity" to "Agent identity",
        "field.generating_identity" to "Generating identity…",
        "approval.visible" to "Visible approval",
        "approval.visible.body" to "After scanning, the phone identity appears here. Access starts only after you approve it.",
        "metric.devices" to "Devices",
        "metric.active_access" to "with active access",
        "metric.capture" to "Capture",
        "metric.system_capability" to "system capability",
        "metric.remote_input" to "Remote input",
        "metric.allowed" to "Allowed",
        "metric.paused" to "Paused",
        "metric.safety_switch" to "safety switch",
        "metric.relay" to "Terminal and files",
        "metric.connected" to "Connected",
        "metric.disconnected" to "Disconnected",
        "metric.outside_lan" to "Access through the app",
        "approval.required" to "Your approval is required",
        "approval.verify" to "Verify the identity before allowing access.",
        "approval.local_phone" to "Phone on the local network · %s",
        "approval.relay_request" to "Remote request · %s",
        "approval.remote_device" to "Remote device",
        "approval.permissions" to
            "Screen, mouse, keyboard, clipboard, terminal, and files. Power-on over the network only when the computer supports it. " +
            "Internet access is not granted here.",
        "approve.processing" to "Working…",
        "reject" to "Reject",
        "approve" to "Approve",
        "devices.authorized_access" to "Authorized access",
        "devices.none" to "No device can control this computer.",
        "devices.sessions.one" to "1 device can start sessions.",
        "devices.sessions.many" to "%d devices can start sessions.",
        "devices.active_count" to "%d active",
        "devices.empty.title" to "No devices yet",
        "devices.empty.body" to "Scan the QR on Home and approve the phone so it appears here.",
        "devices.authorized" to "Authorized",
        "devices.revoked" to "Revoked",
        "devices.ssh_removal_pending" to "SSH removal pending",
        "devices.ssh_removal_pending_detail" to "%s: Aegis access is blocked; SSH key removal is still pending.",
        "devices.ssh_removal_retry" to "Retry SSH removal",
        "devices.ssh_removal_retrying" to "Removing SSH key…",
        "devices.approved_at" to "Approved %s",
        "devices.approved_label" to "Approved",
        "activity.title" to "Agent log",
        "activity.body" to "Local connection, security, and capability events.",
        "activity.events.one" to "1 event",
        "activity.events.many" to "%d events",
        "activity.empty.title" to "No activity yet",
        "activity.empty.body" to "Agent events will appear here when connections or settings change.",
        "log.level.info" to "INFO",
        "log.level.warning" to "WARNING",
        "log.level.error" to "ERROR",
        "settings.relay.title" to "Alternative connection",
        "settings.relay.body" to "Compatibility settings for existing installations.",
        "settings.relay.url" to "Connection address *",
        "settings.relay.url.placeholder" to "https://relay.example.com",
        "settings.relay.id" to "This PC ID (optional)",
        "settings.relay.id.placeholder" to "Aegis can assign one automatically",
        "settings.relay.saving" to "Saving…",
        "settings.relay.save" to "Save and connect",
        "settings.relay.remove" to "Remove alternative connection",
        "settings.relay.rotate_identity" to "Renew connection key",
        "settings.relay.rotate_identity.title" to "Renew key",
        "settings.relay.rotate_identity.body" to
            "Active remote sessions will close and a new key will be created. The old key must authorize the change before it is retired.",
        "settings.relay.rotate_identity.confirm" to "Renew",
        "settings.relay.guide.title" to "How to configure the relay",
        "settings.relay.guide.summary" to
            "The relay lets both devices find each other outside Wi‑Fi. It never receives SSH passwords or video.",
        "settings.relay.guide.step1" to "1. Run or deploy the relay server behind HTTPS.",
        "settings.relay.guide.step2" to "2. Paste its URL here and select Save and connect.",
        "settings.relay.guide.step3" to "3. On Android, use the same URL and the PC ID shown below.",
        "settings.relay.guide.security" to
            "For Internet use HTTPS/WSS, proxy authentication, and persistent storage. For a local test you may use http://PC_IP:8080.",
        "settings.relay.show_guide" to "Show guide",
        "settings.relay.hide_guide" to "Hide guide",
        "settings.access.title" to "Access and privacy",
        "settings.access.body" to "Control what Aegis can do on this computer.",
        "settings.zoom.title" to "Interface zoom",
        "settings.zoom.body" to "Adjust the interface size without changing the display resolution.",
        "settings.zoom.reset" to "Reset to 100%",
        "settings.remote.title" to "Use alternative connection",
        "settings.remote.needs_relay" to "Configure a relay to connect outside your local network.",
        "settings.remote.ready" to "Allow new sessions through the configured relay.",
        "settings.input.title" to "Mouse and keyboard input",
        "settings.input.enabled" to "Approved devices can send input actions.",
        "settings.input.paused" to "Paused: remote mouse and keyboard actions are blocked.",
        "settings.clipboard.title" to "Clipboard synchronization",
        "settings.clipboard.body" to "Share text securely during an active session. Off by default.",
        "settings.autostart.title" to "Start when signing in",
        "settings.autostart.available" to "Open the agent in your user session.",
        "settings.autostart.unavailable" to "Not available on this system.",
        "settings.displays" to "Detected displays",
        "settings.display.origin" to "%d × %d · origin %d, %d",
        "settings.display.primary" to "Primary",
        "settings.language.title" to "Language",
        "settings.language.body" to "The app initially uses the installer's language. You can change it here.",
        "settings.language.system" to "System",
        "settings.language.spanish" to "Español",
        "settings.language.english" to "English",
        "manual.title" to "Manual connection details",
        "manual.body" to "The QR code prepares these details automatically. Use them to set up a manual connection.",
        "manual.host" to "LAN host *",
        "manual.username" to "System username *",
        "manual.fingerprint" to "Computer verification code",
        "manual.algorithm" to "Algorithm",
        "manual.credential" to
            "A password or private key is required and is supplied only by you on Android; Aegis never displays it or includes it in the QR.",
        "manual.unavailable" to "Unavailable",
        "manual.permission" to "Permission required",
        "manual.error" to "Could not detect",
        "settings.application" to "Application",
        "settings.application.body" to "Closing the window ends all connections. Use Hide window in the tray to keep access available.",
        "settings.exit" to "Exit Aegis",
        "settings.nav.heading" to "SETTINGS",
        "settings.nav.access" to "Remote access",
        "settings.nav.privacy" to "Privacy",
        "settings.nav.firewall" to "Firewall",
        "settings.nav.ssh" to "Manual connection",
        "settings.nav.capabilities" to "Capabilities",
        "settings.nav.displays" to "Displays",
        "settings.nav.app" to "Startup and exit",
        "trust.recovery.title" to "Trust store recovery is required",
        "trust.recovery.body" to
            "Linking, revoking, and deleting are blocked so the original file stays intact. Restore a valid backup or confirm a reset to link devices again.",
        "trust.recovery.path" to "Validated backup path",
        "trust.recovery.path.placeholder" to "C:\\path\\authorized-devices.json",
        "trust.recovery.restore" to "Restore backup",
        "trust.recovery.reset" to "Reset and link again",
        "trust.reset.title" to "Reset trust and link devices again?",
        "trust.reset.body" to
            "This replaces the unrecoverable store with an empty one. Devices will need to be linked again. It continues only after this confirmation.",
        "trust.reset.confirm" to "Confirm reset",
        "ufw.title" to "Local network firewall",
        "ufw.body" to
            "Optional rules are added only after you review and authorize them. Aegis never turns the firewall on or changes its defaults.",
        "ufw.inspect" to "Inspect the active local network",
        "ufw.scope" to "Interface %s · %s · TCP 48291 and 48222 only",
        "ufw.review" to "Review firewall authorization",
        "ufw.inactive" to "The firewall is inactive. Aegis will not enable it.",
        "ufw.applied" to "Local-network firewall rules are present.",
        "ufw.consent.title" to "Authorize two local-network-only rules?",
        "ufw.consent.body" to
            "Add TCP 48291 and TCP 48222 only on %s from %s. The firewall must already be active. Aegis will not enable it or change other rules.",
        "ufw.consent.confirm" to "Authorize these rules",
        "capabilities.title" to "System capabilities",
        "capabilities.pairing_server" to "Phone connection",
        "capabilities.openssh" to "Terminal and files",
        "capabilities.capture" to "Screen capture",
        "capabilities.input" to "Input control",
        "relay.title" to "Alternative connection",
        "relay.connected" to "Connected",
        "relay.not_connected" to "Not connected",
        "relay.url" to "URL",
        "relay.not_configured" to "Not configured",
        "relay.device_id" to "Device ID",
        "relay.not_registered" to "Not registered",
        "relay.pending" to "Pending requests",
        "status.available" to "Available",
        "status.unavailable" to "Unavailable",
        "status.checking" to "Checking",
        "status.permission_required" to "Permission required",
        "qr.preparing" to "Preparing QR",
        "qr.description" to "QR code for pairing Aegis Android",
        "permissions.none" to "No active permissions",
        "permissions.prefix" to "Permissions: %s",
        "permission.screen" to "screen",
        "permission.input" to "Mouse and keyboard",
        "permission.terminal" to "terminal",
        "permission.files" to "files",
        "permission.clipboard" to "Share text",
        "permission.wol" to "Wake the PC",
        "permission.remote" to "remote access",
        "time.now" to "now",
        "time.recently" to "recently",
        "status.degraded" to "Degraded",
        "home.ssh.unavailable.title" to "Terminal and files are not ready",
        "home.ssh.unavailable.body" to
            "The Aegis OpenSSH service is not running. Repair or reinstall with the elevated Setup to enable terminal and files.",
        "home.network.public.title" to "This network is marked Public",
        "home.network.public.body" to
            "Setup opens terminal and files only on Private or domain networks. In Windows, mark this network Private: Settings → " +
            "Network & Internet → network properties.",
        "preflight.windows" to "Windows check",
        "preflight.linux" to "Linux check",
        "preflight.compositor.unknown" to "unknown compositor",
        "preflight.capability.operating-system" to "Operating system",
        "preflight.capability.architecture" to "Architecture",
        "preflight.capability.interactive-session" to "Interactive session",
        "preflight.capability.webrtc-native" to "Native WebRTC",
        "preflight.capability.desktop-duplication" to "Desktop duplication",
        "preflight.capability.send-input" to "Send input",
        "preflight.capability.dpapi" to "DPAPI",
        "preflight.capability.openssh-scripts" to "OpenSSH scripts",
        "preflight.capability.openssh-port" to "OpenSSH port",
        "preflight.capability.network-profile" to "Network profile",
        "preflight.capability.data-directory" to "Data directory",
        "preflight.capability.autostart" to "Autostart",
        "preflight.capability.capture" to "Capture",
        "preflight.capability.input" to "Input",
        "preflight.capability.clipboard" to "Clipboard",
        "preflight.capability.session" to "Session",
        "preflight.capability.compositor" to "Compositor",
        "preflight.capability.xdg-desktop-portal" to "XDG portal",
        "preflight.capability.portal-backend" to "Portal backend",
        "preflight.capability.pipewire" to "PipeWire",
        "preflight.capability.dbus-session" to "D-Bus session",
        "preflight.capability.secret-service" to "Secret service",
        "preflight.capability.sshd" to "sshd",
        "preflight.capability.ssh-keygen" to "ssh-keygen",
        "preflight.capability.xdotool-xtest" to "xdotool / XTEST",
        "preflight.capability.ydotool-socket" to "ydotool",
        "preflight.capability.xclip" to "xclip",
        "preflight.capability.wl-copy" to "wl-copy",
        "preflight.capability.wl-paste" to "wl-paste",
        "preflight.capability.portal-bridge" to "Portal bridge",
        "preflight.network.public.detail" to
            "The active network is Public, so terminal and files (TCP 48222) are blocked. Mark the network Private.",
    )

internal fun desktopSpanishCopyKeys(): Set<String> = SPANISH_COPY.keys

internal fun desktopEnglishCopyKeys(): Set<String> = ENGLISH_COPY.keys
